// Automatically generated by astro-icon
// c97839a7d15ed731728dc355d578b53d4bf252e12ae36b6ed16c1c2b6ffc9fba

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "close"
		| "github"
		| "language"
		| "link"
		| "linkedin"
		| "mail"
		| "menu"
		| "moon"
		| "sun"
		| "techs/astro"
		| "techs/css"
		| "techs/firebase"
		| "techs/html"
		| "techs/javascript"
		| "techs/open-props"
		| "techs/php"
		| "techs/pwa"
		| "techs/react"
		| "techs/sass"
		| "techs/tailwindcss"
		| "techs/typescript"
		| "techs/wordpress";
}